name: Build and Test Server

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches-ignore: [ "main" ]

defaults:
    run:
        working-directory: server

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    strategy:
        matrix:
            node-version: [16.x]
            
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Build and Test
      run: |
        npm ci
        npm test